# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1075, 733)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.ui_net_view = NetView(self.central_widget)
        self.ui_net_view.setAccessibleName("")
        self.ui_net_view.setObjectName("ui_net_view")
        self.gridLayout.addWidget(self.ui_net_view, 1, 0, 1, 1)
        self.ui_net_label = QtWidgets.QLabel(self.central_widget)
        self.ui_net_label.setObjectName("ui_net_label")
        self.gridLayout.addWidget(self.ui_net_label, 0, 0, 1, 1)
        main_window.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 23))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.toolbar_play = QtWidgets.QToolBar(main_window)
        self.toolbar_play.setObjectName("toolbar_play")
        main_window.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar_play)
        self.dock = QtWidgets.QDockWidget(main_window)
        self.dock.setObjectName("dock")
        self.dock_widget_contents = QtWidgets.QWidget()
        self.dock_widget_contents.setObjectName("dock_widget_contents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dock_widget_contents)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dock_table = CSTableWidget(self.dock_widget_contents)
        self.dock_table.setObjectName("dock_table")
        self.dock_table.setColumnCount(0)
        self.dock_table.setRowCount(0)
        self.gridLayout_3.addWidget(self.dock_table, 0, 0, 1, 1)
        self.dock.setWidget(self.dock_widget_contents)
        main_window.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dock)
        self.toolbar_view = QtWidgets.QToolBar(main_window)
        self.toolbar_view.setObjectName("toolbar_view")
        main_window.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar_view)
        self.action_step = QtWidgets.QAction(main_window)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/step.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_step.setIcon(icon)
        self.action_step.setObjectName("action_step")
        self.action_node = QtWidgets.QAction(main_window)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/node.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_node.setIcon(icon1)
        self.action_node.setObjectName("action_node")
        self.action_egde = QtWidgets.QAction(main_window)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/edge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_egde.setIcon(icon2)
        self.action_egde.setObjectName("action_egde")
        self.action_stores = QtWidgets.QAction(main_window)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/store.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_stores.setIcon(icon3)
        self.action_stores.setObjectName("action_stores")
        self.action_hits = QtWidgets.QAction(main_window)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/hit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_hits.setIcon(icon4)
        self.action_hits.setObjectName("action_hits")
        self.toolbar_play.addAction(self.action_step)
        self.toolbar_view.addAction(self.action_stores)
        self.toolbar_view.addAction(self.action_hits)

        self.retranslateUi(main_window)
        self.action_step.triggered.connect(main_window.playSteps)
        self.action_stores.triggered.connect(self.ui_net_view.viewStores)
        self.action_hits.triggered.connect(self.ui_net_view.viewHits)
        self.ui_net_view.setLabelText['QString'].connect(self.ui_net_label.setText)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "LICNsim"))
        self.ui_net_label.setText(_translate("main_window", "ui_net_label"))
        self.toolbar_play.setWindowTitle(_translate("main_window", "播放工具栏"))
        self.dock.setWindowTitle(_translate("main_window", "CS表"))
        self.toolbar_view.setWindowTitle(_translate("main_window", "toolBar"))
        self.action_step.setText(_translate("main_window", "下一步"))
        self.action_node.setText(_translate("main_window", "Node"))
        self.action_egde.setText(_translate("main_window", "Egde"))
        self.action_stores.setText(_translate("main_window", "CS信息"))
        self.action_hits.setText(_translate("main_window", "命中率"))

from visualizer import CSTableWidget, NetView
